### ISSUE TITLE
Μήνυμα σε νέα εγκατάσταση (nbg plugin)

### ISSUE THREAD

**Issue by xinomilo** [ellak-monades-aristeias/Woocommerce-Payment-Gateways-Greek-Banks#9]
μόλις κάνω ενεργοποιηση του plugin σε πληρως αναβαθμισμενο wp & woo, παίρνω το μήνυμα : 
The plugin generated 2 characters of unexpected output during activation. If you notice “headers already sent” messages, problems with syndication feeds or other issues, try deactivating or removing this plugin.

δεν έχω προχωρήσει με ρυθμίσεις κτλ και ίσως και να μην γίνει ποτέ αυτό (τεστ σαιτ), απλά αναφέρω το παραπάνω.

**Comment by mekios** [comment]
Σβήσε την πρώτη γραμμή του Simplexml.php

**Comment by xinomilo** [comment]
ευχαριστώ 👍
